### PR TITLE
394 fix resourceIdentifier vs reference comparison

### LINKED ISSUE #394: ResourceIdentifier to a Reference comparison is not working as expected
### Description
Comparing a `ResourceIdentifier` to a `Reference` which contain the same id field value should be render as equal. For example:
A resource identifier that looks as follows:
```
{
   "id": "foo",
   "typeId": "category"
}
```
and a reference that looks as follows: 
```
{
   "id": "foo",
   "typeId": "category"
}
```

Should be rendered as equal and not produce a generate an update action for it. 

### Current Behaviour
When comparing the both resource identifier on a draft and a reference on a resource, the update actions utils perceives them as *not* equal. And would build an update action as a result. Which is wrong behaviour.

### Expected Behaviour
They should be perceived as equal and not build an action since it's not required.

### Context
Most references on drafts are resource identifiers. Therefore, in most cases we will be comparing a reference on a resource and resource identifier on the new draft. Therefore, an update action is not needed when the id fields on both are equal.

### PR DESCRIPTION
**Pull request by heshamMassoud**
#### Summary
Fixes #394 

This PR addresses multiple things related to the same issue #394:

1. Add the [`CommonTypeUpdateActionUtils#buildUpdateActionForReferences`](https://github.com/commercetools/commercetools-sync-java/pull/398/files#diff-1e56c52206999ccd8db44d223e81bde7R58) util which is used to correctly compare any two resourceIdentifiers/references. 

2. When attaching resourceIdentifiers to drafts in tests, we now use `ResourceIdentifier#of` instead of `Category#referenceOfId` in case of categories for example. Since, the second one has type `Reference` and the first one has `ResourceIdentifier`. This way is the more common way to do it, since the draft accepts a `ResourceIdentifier` not the more specific `Reference`. The previously done why was also passing some tests positively, since when comparing a draft to a resource, the resource usually has a `Reference` not a `ResourceIdentifier`. So if the draft also had a `Reference` attached instead of a `ResourceIdentifier`, it means we'll be comparing a `Reference` to a `Reference` which basically wasn't catching the case of #394 so the tests were false positives. 

#### Relevant Issues
#394 

- Tests
    - [x] Unit 
    - [x] Integration
- [x] Documentation
- [x] Add Release Notes entry.

### CODE REVIEW

File: src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java [hunk 1]
```diff
@@ -135,37 +136,6 @@ void sync_WithNewInventory_ShouldCreateInventory() {
         assertValues(oldInventoryAfterSync.get(), QUANTITY_ON_STOCK_2, EXPECTED_DELIVERY_2, RESTOCKABLE_IN_DAYS_2);
     }
 
-    @Test
```
Comment (ahmetoz) [inline src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java]: why did you need to delete this test method?

File: src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java [hunk 2]
```diff
@@ -135,37 +136,6 @@ void sync_WithNewInventory_ShouldCreateInventory() {
...
-        //Ensure old entry values after sync.
-        final Optional<InventoryEntry> oldInventoryAfterSync =
-            getInventoryEntryBySkuAndSupplyChannel(CTP_TARGET_CLIENT, SKU_1, supplyChannelReference);
-        assertThat(oldInventoryAfterSync).isPresent();
-        assertValues(oldInventoryAfterSync.get(), QUANTITY_ON_STOCK_2, EXPECTED_DELIVERY_2, RESTOCKABLE_IN_DAYS_2);
-        assertThat(oldInventoryAfterSync.get().getSupplyChannel().getId()).isEqualTo(supplyChannelReference.getId());
-    }
-
     @Test
     void sync_WithKeyToExistingSupplyChannelInPlaceOfReferenceId_ShouldUpdateInventory() {
```
Comment (ahmetoz) [inline src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java]: should we change the method name in here from ReferenceId to ResourceIdentifierWithId or Key?

File: src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java [hunk 3]
```diff
@@ -179,9 +149,7 @@ void sync_WithKeyToExistingSupplyChannelInPlaceOfReferenceId_ShouldUpdateInvento
          * Prepare InventoryEntryDraft of sku SKU_1 and reference to supply channel of key SUPPLY_CHANNEL_KEY_1.
          * Please note that the key is provided in place of Referenced id.
          */
-        final Reference<Channel> supplyChannelReference = Channel.referenceOfId(SUPPLY_CHANNEL_KEY_1);
-        assertThat(supplyChannelReference.getObj()).isNull();
-        assertThat(supplyChannelReference.getId()).isEqualTo(SUPPLY_CHANNEL_KEY_1);
+        final ResourceIdentifier<Channel> supplyChannelReference = ResourceIdentifier.ofId(SUPPLY_CHANNEL_KEY_1);
```
Comment (ahmetoz) [inline src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java]: why not `ResourceIdentifier.ofKey(SUPPLY_CHANNEL_KEY_1);` ?

File: src/main/java/com/commercetools/sync/categories/utils/CategoryReferenceReplacementUtils.java [hunk 4]
```diff
@@ -38,8 +38,8 @@
             .map(category -> {
```
Comment (ahmetoz) [inline src/main/java/com/commercetools/sync/categories/utils/CategoryReferenceReplacementUtils.java]: maybe we need to update java docs in here from references to resourceidentifiers like 
`the categories to replace their {@link ResourceIdentifier} ids with keys...`
 wdyt ?

File: src/main/java/com/commercetools/sync/commons/utils/SyncUtils.java [hunk 5]
```diff
@@ -52,6 +56,33 @@
...
+     * @param keyInReferenceSupplier the supplier to execute and return its result if the {@code reference} was
+     *                               expanded.
+     *
+     * @return returns the result of the {@code keyInReferenceSupplier} if the {@code reference} was expanded.
+     *         Otherwise, it returns the supplied reference as is.
+     */
+    @Nullable
+    public static <T> ResourceIdentifier<T> getResourceIdentifierWithKeyReplaced(
+        @Nullable final Reference<T> reference,
+        @Nonnull final Supplier<ResourceIdentifier<T>> keyInReferenceSupplier) {
```
Comment (ahmetoz) [inline src/main/java/com/commercetools/sync/commons/utils/SyncUtils.java]: maybe it's better if we use ResourceIdentifier in java doc instead of the reference to make it different with getReferenceWithKeyReplaced's Javadoc. both javadocs looks same except the method name.

File: src/test/java/com/commercetools/sync/commons/utils/SyncUtilsTest.java [hunk 6]
```diff
@@ -117,36 +119,63 @@ void batchElements_WithNegativeSize_ShouldReturnNoBatches() {
...
+    }
+
+    @Test
+    void getReferenceWithKeyReplaced_WithNonExpandedCategoryReference_ShouldReturnReferenceWithoutReplacedKey() {
         final String categoryUuid = UUID.randomUUID().toString();
         final Reference<Category> categoryReference = Reference.ofResourceTypeIdAndId(Category.referenceTypeId(),
             categoryUuid);
 
-        final Reference<Category> keyReplacedReference = replaceReferenceIdWithKey(categoryReference,
+        final ResourceIdentifier<Category> keyReplacedReference = getReferenceWithKeyReplaced(categoryReference,
```
Comment (ahmetoz) [inline src/test/java/com/commercetools/sync/commons/utils/SyncUtilsTest.java]: why not Reference, because we are testing `getReferenceWithKeyReplaced`

File: src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java [hunk 7]
```diff
@@ -119,6 +121,27 @@ public static ProductDraftBuilder createProductDraftBuilder(@Nonnull final Strin
...
+
+        final List<Reference<Category>> references = categoryResourceIdentifiers
+            .stream()
+            .map(categoryResourceIdentifier -> Category.referenceOfId(categoryResourceIdentifier.getId()))
+            .collect(toList());
+        return createRandomCategoryOrderHints(references);
+    }
 
     /**
      * Given a {@link List} of {@link Category}, this method returns an instance of {@link CategoryOrderHints}
```
Comment (ahmetoz) [inline src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java]: ``Given a {@link Set} of {@link Category} {@link Reference}``

File: src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java [hunk 8]
```diff
@@ -119,6 +121,27 @@ public static ProductDraftBuilder createProductDraftBuilder(@Nonnull final Strin
...
+     * {@link Set} as a key and a random categoryOrderHint which is a {@link String} containing a random double value
+     * between 0 and 1 (exclusive).
+     *
+     * <p>Note: The random double value is generated by the {@link ThreadLocalRandom#current()} nextDouble method.
+     *
+     * @param categoryResourceIdentifiers set of resource identifiers of categories to build categoryOrderHints for.
+     * @return an instance of {@link CategoryOrderHints} containing a categoryOrderHint for each category in the
+     *         supplied set of category resource identifiers.
+     */
+    public static CategoryOrderHints createRandomCategoryOrderHints(
```
Comment (ahmetoz) [inline src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java]: I could not see any usage of this method from idea.

File: src/main/java/com/commercetools/sync/commons/utils/CommonTypeUpdateActionUtils.java [hunk 9]
```diff
@@ -29,13 +31,57 @@
...
+     * @param oldResourceIdentifier the old resource identifier
+     * @param newResourceIdentifier the new resource identifier
+     * @param <T>                   the type of the old resource identifier
+     * @param <S>                   the type of the new resource identifier
+     * @return true or false depending if the resource identifiers have the same id.
+     */
+    public static <T extends ResourceIdentifier, S extends ResourceIdentifier> boolean areResourceIdentifiersEqual(
+        @Nullable final T oldResourceIdentifier, @Nullable final S newResourceIdentifier) {
+
+        final String oldId = ofNullable(oldResourceIdentifier).map(ResourceIdentifier::getId).orElse(null);
```
Comment (ahmetoz) [inline src/main/java/com/commercetools/sync/commons/utils/CommonTypeUpdateActionUtils.java]: what happens if ResourceIdentifiers are key-based ? 
https://docs.commercetools.com/http-api-types.html#resourceidentifier-by-key

File: src/integration-test/java/com/commercetools/sync/integration/commons/utils/CategoryITUtils.java [hunk 10]
```diff
@@ -280,10 +281,11 @@ private static boolean hasADeletedAncestor(@Nonnull final Category category,
      *         {@link Category}.
      */
     @Nonnull
-    public static List<Reference<Category>> getReferencesWithKeys(@Nonnull final List<Category> categories) {
```
[the remark this answers is not in the document]
Comment (heshamMassoud) [reply src/integration-test/java/com/commercetools/sync/integration/commons/utils/CategoryITUtils.java]: https://github.com/commercetools/commercetools-sync-java/pull/398/commits/6f488a919289755fc53cadb71ce1d4197ade3041

File: src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java (hunk 1 above)
Comment (heshamMassoud) [reply src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java]: because I noticed its a redundant test, it's testing nothing special compared to `sync_WithKeyToExistingSupplyChannelInPlaceOfReferenceId_ShouldUpdateInventory` for example.

File: src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java (hunk 3 above)
Comment (heshamMassoud) [reply src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java]: because this is the way we do reference resolution on the sync java library in general: We always provide the key in place of the id field (for consistency) since there still (will change in the future) exists references which are of type `Reference` not `ResourceIdentifier`. And in a `Reference` there is no `key` field, so we misuse the `id` field for it. 

However, this ought to be changed very soon.

File: src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java (hunk 2 above)
Comment (heshamMassoud) [reply src/integration-test/java/com/commercetools/sync/integration/inventories/InventorySyncIT.java]: 602b8cb

File: src/main/java/com/commercetools/sync/categories/utils/CategoryReferenceReplacementUtils.java (hunk 4 above)
Comment (heshamMassoud) [reply src/main/java/com/commercetools/sync/categories/utils/CategoryReferenceReplacementUtils.java]: 17ea123

File: src/main/java/com/commercetools/sync/commons/utils/SyncUtils.java (hunk 5 above)
Comment (heshamMassoud) [reply src/main/java/com/commercetools/sync/commons/utils/SyncUtils.java]: but actually the javadoc mentions the reference that is passed not the returned `ResourceIdentifier`, so I am not entirely sure which part of the javadoc should be changed

File: src/test/java/com/commercetools/sync/commons/utils/SyncUtilsTest.java (hunk 6 above)
Comment (heshamMassoud) [reply src/test/java/com/commercetools/sync/commons/utils/SyncUtilsTest.java]: nice catch: 41e6358

File: src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java (hunk 7 above)
Comment (heshamMassoud) [reply src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java]: why? It is still a list here :)

File: src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java (hunk 8 above)
Comment (heshamMassoud) [reply src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java]: In this IT https://github.com/commercetools/commercetools-sync-java/pull/398/files#diff-4b6cdd198bf924968ff292406ff87580R138

File: src/main/java/com/commercetools/sync/commons/utils/CommonTypeUpdateActionUtils.java (hunk 9 above)
Comment (heshamMassoud) [reply src/main/java/com/commercetools/sync/commons/utils/CommonTypeUpdateActionUtils.java]: This is not how the sync java should be used (as of now). Check the documentations:

https://commercetools.github.io/commercetools-sync-java/doc/usage/PRODUCT_SYNC/#sync-list-of-product-drafts

File: src/main/java/com/commercetools/sync/commons/utils/SyncUtils.java (hunk 5 above)
Comment (ahmetoz) [reply src/main/java/com/commercetools/sync/commons/utils/SyncUtils.java]: oh you are right 👍

File: src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java (hunk 7 above)
Comment (ahmetoz) [reply src/test/java/com/commercetools/sync/products/ProductSyncMockUtils.java]: probably I was reading the other one, methods have the same name. 🙈

File: src/main/java/com/commercetools/sync/commons/utils/CommonTypeUpdateActionUtils.java (hunk 9 above)
Comment (ahmetoz) [reply src/main/java/com/commercetools/sync/commons/utils/CommonTypeUpdateActionUtils.java]: hmm, I did not realize that before 👍
